import yagmail

# --- Configuration ---
sender_email = "paulsedward88@gmail.com"
app_password = "eehf caik pvdp dpau"  # Use Gmail App Password
recipient_email = "digitaladoption-and-innovation@swiss.com"

# --- AI-generated text (placeholder) ---
ai_generated_text = "Hello! This is a test email generated by my AI agent."

# --- Send the email ---
try:
    yag = yagmail.SMTP(user=sender_email, password=app_password)
    yag.send(
        to=recipient_email,
        subject="Test Email from AI Agent",
        contents=ai_generated_text
    )
    print("✅ Email sent successfully!")
except Exception as e:
    print(f"❌ Failed to send email: {e}")